package works.mees.jiib.theme

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Test
import java.util.Locale

/**
 * Golden-conformance for the D-11 bed-mesh OKLCH sequential ramp: the Kotlin baker [OklchRamp]
 * must reproduce `app/src/test/resources/oklch-ramp-golden.json`'s `ramp[]` BIT-FOR-BIT (32
 * quantized lowercase `#rrggbb` stops, no epsilon — like [PaletteGoldenTest] vs `color-golden.json`).
 *
 * The committed fixture is the canonical spec the Kotlin implements TO (NEVER the reverse): it is
 * generated by the independent oracle `tools/oklch-ramp-oracle.mjs`. If a stop mismatches, fix the
 * Kotlin baker — do NOT regenerate the fixture from Kotlin output (that collapses the golden test
 * into a tautology). If the locked control points themselves must change, re-run the oracle.
 *
 * Fixture parameterization (LOCKED): 32 stops, endpoints inclusive, three OKLCH control points
 * low(0.45 0.12 255) → mid(0.65 0.13 150) → high(0.85 0.15 95), piecewise-linear across two segments
 * split at the mid control point anchored at stop index 15, hue along the shorter arc.
 */
class OklchRampTest {

    private val ramp: List<String> by lazy {
        val text = javaClass.getResourceAsStream("/oklch-ramp-golden.json")!!
            .bufferedReader().use { it.readText() }
        Json.parseToJsonElement(text).jsonObject["ramp"]!!.jsonArray
            .map { it.jsonPrimitive.content }
    }

    /** Opaque ARGB int → lowercase `#rrggbb` (drop alpha), matching the fixture's hex format. */
    private fun argbToHex(argb: Int): String {
        val r = (argb ushr 16) and 0xFF
        val g = (argb ushr 8) and 0xFF
        val b = argb and 0xFF
        return String.format(Locale.US, "#%02x%02x%02x", r, g, b)
    }

    @Test
    fun bakedRamp_matchesGoldenFixtureBitForBit() {
        val baked = OklchRamp.bedMeshRampStops().map { argbToHex(it) }
        assertEquals("ramp stop count", ramp.size, baked.size)
        ramp.forEachIndexed { i, expected ->
            assertEquals("ramp[$i]", expected, baked[i])
        }
    }

    @Test
    fun rampEndpoints_areControlPointsInclusive() {
        val baked = OklchRamp.bedMeshRampStops().map { argbToHex(it) }
        // endpointsInclusive = true: stop 0 == low control point's hex, stop 31 == high control point's hex.
        assertEquals("ramp stop 0 (low control point)", ramp.first(), baked.first())
        assertEquals("ramp stop 31 (high control point)", ramp.last(), baked.last())
    }

    /** Per-channel near-equality (≤2/255) — OKLCH round-trip of an in-gamut sRGB color is near-exact. */
    private fun assertArgbClose(msg: String, expected: Int, actual: Int) {
        val er = (expected ushr 16) and 0xFF; val eg = (expected ushr 8) and 0xFF; val eb = expected and 0xFF
        val ar = (actual ushr 16) and 0xFF; val ag = (actual ushr 8) and 0xFF; val ab = actual and 0xFF
        val ok = Math.abs(er - ar) <= 2 && Math.abs(eg - ag) <= 2 && Math.abs(eb - ab) <= 2
        org.junit.Assert.assertTrue("$msg: expected ${argbToHex(expected)} got ${argbToHex(actual)}", ok)
    }

    @Test
    fun themedRamp_endpointsAreLowAndHigh_andCount() {
        // 15.2-06: theme-derived ramp — LOW = a data-pool color, HIGH = the accent. Endpoints inclusive.
        val low = 0xFF1E66F5.toInt()  // a saturated blue (in-gamut data-pool stand-in)
        val high = 0xFFE6A817.toInt() // a saturated amber/gold (accent stand-in)
        val baked = OklchRamp.themedRampStops(low, high)
        assertEquals("themed ramp stop count", OklchRamp.stopCount, baked.size)
        assertArgbClose("themed ramp stop 0 == LOW (pool)", low, baked.first())
        assertArgbClose("themed ramp stop ${baked.lastIndex} == HIGH (accent)", high, baked.last())
    }

    @Test
    fun themedRamp_bothCenterStopsArePassedNeutral_soFracHalfIsExact() {
        // The mid neutral is a theme-INDEPENDENT fixed color (BedMeshScreen passes the blend of the
        // dark+light outlines). With an EVEN stop count, a rendered frac=0.5 samples position 15.5 and
        // BLENDS the two center stops — so BOTH center stops (HALF-1 and HALF) must equal the neutral
        // for the zero-deviation midplane to render exactly the neutral (not biased toward low).
        val low = 0xFF1E66F5.toInt()   // saturated blue
        val high = 0xFFE6A817.toInt()  // saturated amber
        val mid = 0xFF787F8B.toInt()   // the fixed mesh neutral (#787F8B)
        val baked = OklchRamp.themedRampStops(low, high, mid)
        val half = OklchRamp.stopCount / 2
        // Both center stops equal the neutral → the renderer's frac=0.5 blend of them is the neutral too.
        assertArgbClose("center stop HALF == neutral", mid, baked[half])
        assertArgbClose("center stop HALF-1 == neutral", mid, baked[half - 1])
    }

    @Test
    fun themedRamp_reTintsWhenEndpointsChange() {
        // Re-baking with different endpoints yields a different ramp (proves it follows the theme).
        val a = OklchRamp.themedRampStops(0xFF1E66F5.toInt(), 0xFFE6A817.toInt())
        val b = OklchRamp.themedRampStops(0xFF40A02B.toInt(), 0xFFD20F39.toInt())
        org.junit.Assert.assertFalse("ramp must change when theme endpoints change", a.contentEquals(b))
    }
}
