package works.mees.dinghy.theme

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Test
import java.util.Locale

/**
 * Golden-conformance for the D-11 bed-mesh OKLCH sequential ramp: the Kotlin baker [OklchRamp]
 * must reproduce `app/src/test/resources/oklch-ramp-golden.json`'s `ramp[]` BIT-FOR-BIT (32
 * quantized lowercase `#rrggbb` stops, no epsilon — like [PaletteGoldenTest] vs `color-golden.json`).
 *
 * The committed fixture is the canonical spec the Kotlin implements TO (NEVER the reverse): it is
 * generated by the independent oracle `tools/oklch-ramp-oracle.mjs`. If a stop mismatches, fix the
 * Kotlin baker — do NOT regenerate the fixture from Kotlin output (that collapses the golden test
 * into a tautology). If the locked control points themselves must change, re-run the oracle.
 *
 * Fixture parameterization (LOCKED): 32 stops, endpoints inclusive, three OKLCH control points
 * low(0.45 0.12 255) → mid(0.65 0.13 150) → high(0.85 0.15 95), piecewise-linear across two segments
 * split at the mid control point anchored at stop index 15, hue along the shorter arc.
 */
class OklchRampTest {

    private val ramp: List<String> by lazy {
        val text = javaClass.getResourceAsStream("/oklch-ramp-golden.json")!!
            .bufferedReader().use { it.readText() }
        Json.parseToJsonElement(text).jsonObject["ramp"]!!.jsonArray
            .map { it.jsonPrimitive.content }
    }

    /** Opaque ARGB int → lowercase `#rrggbb` (drop alpha), matching the fixture's hex format. */
    private fun argbToHex(argb: Int): String {
        val r = (argb ushr 16) and 0xFF
        val g = (argb ushr 8) and 0xFF
        val b = argb and 0xFF
        return String.format(Locale.US, "#%02x%02x%02x", r, g, b)
    }

    @Test
    fun bakedRamp_matchesGoldenFixtureBitForBit() {
        val baked = OklchRamp.bedMeshRampStops().map { argbToHex(it) }
        assertEquals("ramp stop count", ramp.size, baked.size)
        ramp.forEachIndexed { i, expected ->
            assertEquals("ramp[$i]", expected, baked[i])
        }
    }

    @Test
    fun rampEndpoints_areControlPointsInclusive() {
        val baked = OklchRamp.bedMeshRampStops().map { argbToHex(it) }
        // endpointsInclusive = true: stop 0 == low control point's hex, stop 31 == high control point's hex.
        assertEquals("ramp stop 0 (low control point)", ramp.first(), baked.first())
        assertEquals("ramp stop 31 (high control point)", ramp.last(), baked.last())
    }
}
